Implement OAuth2 authentification
KilianPAGEOT/DashFrame pull request #33
Opened 2022-11-07 14:43 UTC by Mathiso00

closes#8

2022-11-07 20:36 UTC, MisterPeModder requested changes

2022-11-07 20:36 UTC, MisterPeModder commented on front/src/api/runtime.ts
> +  public async request(
The files under `api/` cannot be edited by hand as they are auto-generated, please use the proper abstractions instead. (like the one example in App.vue)

2022-11-07 20:36 UTC, MisterPeModder commented on front/cypress/support/commands.ts
> +// Cypress.Commands.add('login', (username, password) => { ... })
was this intentional, looks like a Search & Replace operation went a little overboard there.

2022-11-07 20:36 UTC, MisterPeModder commented on build.gradle
> +    //implementation "org.springframework:spring-boot.security.oauth2.core.user"
It is necessary to add this dependency as a comment?

2022-11-07 20:36 UTC, MisterPeModder commented on front/src/api/models/index.ts
> +   * An username/username, unique accross service instances of a user
was this intentional, looks like a Search & Replace operation went a little overboard there.

Plus this file should not be edited by hand.

2022-11-07 20:36 UTC, MisterPeModder commented on src/main/java/com/github/dashframe/DashframeApplication.java
> +import org.springframework.context.annotation.ComponentScan;
These imports are unused.

2022-11-07 20:36 UTC, MisterPeModder commented on src/main/java/com/github/dashframe/config/SecurityConfig.java
> +            .defaultSuccessUrl("/api/v1/userOAuth2", true)
Uppercase letters in an URL are to be avoided, prefer the use of `kebab-case` when you need multiple words.
Although in this case, you may want to merge this route with @KilianPAGEOT's `/users` route using a query parameter (e.g. `/api/v1/users?oauth2=1`)

2022-11-07 20:36 UTC, MisterPeModder commented on src/main/java/com/github/dashframe/config/SecurityConfig.java
> +    }*/
Is this commented code intentional?

2022-11-07 20:36 UTC, MisterPeModder commented on src/main/java/com/github/dashframe/config/WebMvcConfig.java
> +import org.springframework.web.servlet.config.annotation.CorsRegistry;
Unused import, watch out for warnings!

2022-11-07 20:36 UTC, MisterPeModder commented on src/main/java/com/github/dashframe/rest/LoginController.java
> +public class LoginController extends HttpServlet {
Beware of formatting! use `npm run format`

2022-11-07 20:36 UTC, MisterPeModder commented on src/main/java/com/github/dashframe/rest/LoginController.java
> +    @GetMapping("/userOAuth2")
See the above comment about usage of upper case letters.

2022-11-07 20:36 UTC, MisterPeModder commented on src/main/java/com/github/dashframe/rest/LoginController.java
> +        response.sendRedirect("http://localhost:5176");
The `http://localhost:5176` exists in debug mode ***ONLY***.  
In release mode, the url would look like `http://localhost:8080`, or ideally `https://dashframe.fr`

2022-11-07 20:36 UTC, MisterPeModder commented on src/main/java/com/github/dashframe/rest/LoginController.java
> +        if (authToken.isAuthenticated()) {
The code looks quite scary, a bit of documentation wouldn't hurt

2022-11-07 20:46 UTC, Mathiso00 commented on front/cypress/support/commands.ts
> +// Cypress.Commands.add('login', (username, password) => { ... })
it's refactor in Intellij when i change email by username in User model

2022-11-07 20:49 UTC, Mathiso00 commented on build.gradle
> +    //implementation "org.springframework:spring-boot.security.oauth2.core.user"
This dependency is useless for me and I think I add it when I was testing a code found on the internet

2022-11-07 20:49 UTC, Mathiso00 commented on front/src/api/models/index.ts
> +   * An username/username, unique accross service instances of a user
Just refactor of intellij

2022-11-07 20:51 UTC, Mathiso00 commented on src/main/java/com/github/dashframe/config/SecurityConfig.java
> +    }*/
just an old code

2022-11-07 20:53 UTC, Mathiso00 commented on src/main/java/com/github/dashframe/DashframeApplication.java
> +import org.springframework.context.annotation.ComponentScan;
I fix that

2022-11-07 20:53 UTC, Mathiso00 commented on src/main/java/com/github/dashframe/config/WebMvcConfig.java
> +import org.springframework.web.servlet.config.annotation.CorsRegistry;
I fix that

2022-11-07 20:54 UTC, Mathiso00 commented on src/main/java/com/github/dashframe/config/SecurityConfig.java
> +            .defaultSuccessUrl("/api/v1/userOAuth2", true)
I replace by users-oauth2

2022-11-07 20:54 UTC, Mathiso00 commented on src/main/java/com/github/dashframe/config/SecurityConfig.java
> +            .defaultSuccessUrl("/api/v1/userOAuth2", true)
And we see for merge route tomorrow

2022-11-07 20:55 UTC, Mathiso00 commented on src/main/java/com/github/dashframe/rest/LoginController.java
> +    @GetMapping("/userOAuth2")
users-oauth2

2022-11-07 20:55 UTC, Mathiso00 commented on src/main/java/com/github/dashframe/rest/LoginController.java
> +public class LoginController extends HttpServlet {
I exec npm run format

2022-11-07 20:56 UTC, Mathiso00 commented on src/main/java/com/github/dashframe/rest/LoginController.java
> +        response.sendRedirect("http://localhost:5176");
Maybe but for the moment we can't do otherwise

2022-11-07 20:57 UTC, Mathiso00 commented on src/main/java/com/github/dashframe/rest/LoginController.java
> +        if (authToken.isAuthenticated()) {
Yes a do that and repush all change

2022-11-08 20:45 UTC, Mathiso00 commented
Pb with Principal OAuth2 not return user

2022-11-09 10:11 UTC, MisterPeModder approved these changes

2022-11-09 10:36 UTC, merged